// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfMlo6CZlCWEQdIzwpDGnCaiQhXUuNhjI',
    appId: '1:555843875907:web:46ba685cb7d55ee1bb50f6',
    messagingSenderId: '555843875907',
    projectId: 'medco-e2ba4',
    authDomain: 'medco-e2ba4.firebaseapp.com',
    storageBucket: 'medco-e2ba4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqYtH_2n8BPXvY9JtggICJFGnDlTkTSyE',
    appId: '1:555843875907:android:1c31728f566fb7cbbb50f6',
    messagingSenderId: '555843875907',
    projectId: 'medco-e2ba4',
    storageBucket: 'medco-e2ba4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-nvYDTaNTDM0_82uHoP3ZP2w2BQVJl5M',
    appId: '1:555843875907:ios:aec2803e32f34066bb50f6',
    messagingSenderId: '555843875907',
    projectId: 'medco-e2ba4',
    storageBucket: 'medco-e2ba4.appspot.com',
    iosBundleId: 'com.example.pdl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-nvYDTaNTDM0_82uHoP3ZP2w2BQVJl5M',
    appId: '1:555843875907:ios:deca976c3d8e4f1ebb50f6',
    messagingSenderId: '555843875907',
    projectId: 'medco-e2ba4',
    storageBucket: 'medco-e2ba4.appspot.com',
    iosBundleId: 'com.example.pdl.RunnerTests',
  );
}
